version: '2'
services:
    cuyoaval-app:
        image: cuyoaval
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cuyoaval-mysql:3306/cuyoaval?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cuyoaval-mysql:
        extends:
            file: mysql.yml
            service: cuyoaval-mysql
